source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'IPaDownloadManager_Example' do
  pod 'IPaDownloadManager', :path => '../'

  target 'IPaDownloadManager_Tests' do
    inherit! :search_paths

    
  end
end
